# Generated by Django 3.0.2 on 2020-10-06 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('votingsessions', '0001_initial'),
        ('tokendb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('tx_hash', models.CharField(max_length=100)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_payments', to='tokendb.Token')),
                ('voting_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_payments', to='votingsessions.VotingSession')),
            ],
        ),
    ]
