# Generated by Django 3.1.2 on 2020-10-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingpayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingpayment',
            name='tx_from_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
