# Generated by Django 3.1.2 on 2020-10-08 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingpayment', '0002_votingpayment_tx_from_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingpayment',
            name='tx_from_address',
        ),
    ]
