# Generated by Django 3.1.2 on 2020-10-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=40)),
                ('logo_url', models.URLField()),
                ('pool_url', models.URLField()),
                ('pool_stats_api_url', models.URLField()),
            ],
        ),
    ]
