# Generated by Django 3.1.2 on 2020-10-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingsessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingsession',
            name='hidden_tokens_id',
            field=models.TextField(default='', max_length=400),
        ),
    ]
