# Generated by Django 3.0.2 on 2020-09-25 13:23

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=30)),
                ('logo', versatileimagefield.fields.VersatileImageField(upload_to='tokenlogos/')),
                ('homepage_url', models.URLField()),
                ('algo', models.CharField(max_length=30)),
                ('is_archived', models.BooleanField(default=False)),
                ('has_won', models.BooleanField(default=False)),
            ],
        ),
    ]
