# Generated by Django 3.1.2 on 2020-10-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokendb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='added_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='won_date',
            field=models.DateField(null=True),
        ),
    ]
